### ISSUE TITLE
Error building projects using Govflow as dependency: migrate cli source code not found

### ISSUE THREAD

**Issue by amirozer** [govflow/govflow#39] opened 2021-12-26 13:40 UTC
When building a project using 0.0.18-alpha, I'm getting the following error:

```#8 16.85 npm ERR! code ENOENT
#8 16.85 npm ERR! syscall chmod
#8 16.85 npm ERR! path /app/node_modules/@govflow/govflow/cli/migrate
#8 16.85 npm ERR! errno -2
#8 16.86 npm ERR! enoent ENOENT: no such file or directory, chmod '/app/node_modules/@govflow/govflow/cli/migrate'
#8 16.86 npm ERR! enoent This is related to npm not being able to find a file.
#8 16.86 npm ERR! enoent 
```

*Not sure whether this is an issue with the Govflow project/package or there is some adaptation required on my project to support this

**Comment by pwalsh** [comment] 2021-12-27 06:46
Relates to my comment here https://github.com/govflow/govflow/issues/36#issuecomment-999542612

>  current problem in 0.0.18-alpha may just be because of missing file extension 

The issue is definitely in Gov Flow, fixing.

**Comment by pwalsh** [comment] 2021-12-27 07:25
Should be resolved in https://github.com/govflow/govflow/commit/1318330c68b3f62e6697079498a7017cecb42018 but I will verify with a build from NPM (did verify locally with global install)

**Comment by pwalsh** [comment] 2021-12-27 07:36
Fixed. `npm run build` in internal codebase with Gov Flow `0.0.19-alpha` as a dependency, builds without errors.

**Closed by pwalsh** 2021-12-27 07:36 UTC
